### ISSUE TITLE
'>f8' type arrays will not convert to VTK

### ISSUE THREAD

**Issue by josephburkhart** [prs513rosewood/uvw#1]
When trying to create a rectilinear grid from numpy arrays, I got an error if my arrays were formatted with the data type '>f8': `TypeError: Array dtype >f8 is not supported by VTK`. This seems similar to [an issue recently reported for pyvista (#540)](https://github.com/pyvista/pyvista/issues/540#issue-550434838).

The following code raised the error:

```
from uvw import RectilinearGrid, DataArray
import numpy as np

data = np.zeros((5,5,5))

#xdim = np.array([0,1,2,3,4]).astype('>f8')
#ydim = np.array([0,1,2,3,4]).astype('>f8')
#zdim = np.array([0,1,2,3,4]).astype('>f8')

grid = RectilinearGrid('data.vtr', (ydim, xdim, zdim), compression = True)
grid.addPointData(DataArray(data, range(3), 'data'))
grid.write()
```
Changing `xdim`, `ydim`, and `zdim` as follows resolved the error:

```
xdim = np.array([0,1,2,3,4], dtype=np.float64)
ydim = np.array([0,1,2,3,4], dtype=np.float64)
zdim = np.array([0,1,2,3,4], dtype=np.float64)
```
While this may not matter much for cases where the arrays are defined within the code, it can cause problems when data is imported from other files that may have strange formatting.

(Sorry if my terminology is bad, or if this isn't a proper issue. I'm very new to github.)

System info:
```
OS: Windows 10 Home
Architecture: 64bit

Python 3.7.6
uvw 0.3.1
numpy 1.18.1
```

**Comment by prs513rosewood** [comment]
Hi @BotDoubt ,

Thanks for reporting the error (and sorry I took a while to take notice). I've not gotten around implementing endianness in uvw. It's defined on a file-wide basis in VTK files, so setting it as an option in the file-object construction should be pretty easy. I should be able to fix that pretty soon.

**Comment by prs513rosewood** [comment]
Issue should be fixed now. To adapt your code for big endian, you should do something like:

```python
from uvw import RectilinearGrid, DataArray
import numpy as np

data = np.zeros((5,5,5)).astype('>f8')

xdim = np.array([0,1,2,3,4]).astype('>f8')
ydim = np.array([0,1,2,3,4]).astype('>f8')
zdim = np.array([0,1,2,3,4]).astype('>f8')

grid = RectilinearGrid('data.vtr', (ydim, xdim, zdim), compression = True, byte_order='BigEndian')
grid.addPointData(DataArray(data, range(3), 'data'))
grid.write()
```
