### ISSUE TITLE
Number of Nodes in HEXAHEDRON elements

### ISSUE THREAD

**Issue by nameless2342** [prs513rosewood/uvw#3]
Hello,

I think I found a small error in the "unstructured.py"-part. The Hexahedron type should only have 8 nodes instead of 9 in the NODES_PER_CELL list.

CellType.HEXAHEDRON: 8, instead of CellType.HEXAHEDRON: 9, in line 65. This corrects a few errors I had using the .vtu files with paraview such as clipping elements.

Best greetings and thanks - very helpful stuff

**Comment by prs513rosewood** [comment]
Good catch, thanks!
