### ISSUE TITLE
Number of tuples

### ISSUE THREAD

**Issue by davidcortesortuno** [prs513rosewood/uvw#6]
Hi, I'm creating an `ImageData` file, and when writing the file, the `NumberOfTuples` property produces the size of the flattened data rather than the number of n-component elements in the data array. For instance

```
grid = uvw.ImageData('test_vtk.vti', [(-10., 10.), (-5, 5), (-5, 5)], [3, 3, 2], compression=True)
grid.addCellData(uvw.DataArray(np.arange(1., 9.).reshape(-1, 2), spatial_axes=[0], name='x0d'))
```
 Produces a `vti` file with `NumberOfTuples=8` rather than `4` which is is the number of pair data values I set. 
Is the `NumberOfTuples` property necessary? I think the VTK file works as well without this property but it might be needed to allocate memory properly. There is very little documentation of this value in the VTK docs.

I found that the array is flattened here:

https://github.com/prs513rosewood/uvw/blob/6210d6996f78fd232725e127ff764cc8467c674f/uvw/data_array.py#L102

**Comment by prs513rosewood** [comment]
It's been so long since I wrote this code that I have no idea what `NumberOfTuples` is supposed to be. What kind of problem are you having due to this ?

**Comment by davidcortesortuno** [comment]
No problem at all, it just seems Paraview ignores this parameter. But maybe it is necessary for memory allocation?

**Comment by prs513rosewood** [comment]
I don't know VTK very well, so it's hard for me to say. I expect one could reconstruct the data size from the number of components and the topology of the support, maybe that's what is done internally. In any case, since this is not causing problems I'll close the issue.
