### ISSUE TITLE
ValueError: cannot reshape array of size 90 into shape (11,5,3)  tests/test_parallel.py:128: ValueError

### ISSUE THREAD

**Issue by carlosal1015** [prs513rosewood/uvw#9]
Hi, when I run pytest this test test_parallel.py is failing.

I attach the log file: [python-uvw-0.7.0-1-x86_64-check.log](https://github.com/user-attachments/files/17108211/python-uvw-0.7.0-1-x86_64-check.log).

**Comment by prs513rosewood** [comment]
Are you running these tests in parallel ?

**Comment by carlosal1015** [comment]
I am running [this line](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=python-uvw#n29). Should I run `mpiexec` or `mpirun` before pytest?
```
cd uvw
python -m venv --system-site-packages test-env
test-env/bin/python -m pytest
```

**Comment by prs513rosewood** [comment]
Ah I think I see the error, it seems you're missing a dependency on [pytest-mpi](https://pypi.org/project/pytest-mpi/) which creates the `pytest.mpi.mpi` and `pytest.mpi.mpi_skip` decorators. The parallel tests are normally skipped when run in sequential, but that does not happen when pytest-mpi is missing.

To run the parallel tests:
```
mpirun -np 2 pytest --only-mpi
```

**Comment by carlosal1015** [comment]
Many thanks, now I see it is running in parallel. With this command few errors: [python-uvw-0.7.0-1-x86_64-check.log](https://github.com/user-attachments/files/17149952/python-uvw-0.7.0-1-x86_64-check.log)
```
mpirun -np 2 test-env/bin/python -m pytest tests
```
With this command no errors, but few tests selected: [python-uvw-0.7.0-1-x86_64-check.log](https://github.com/user-attachments/files/17149963/python-uvw-0.7.0-1-x86_64-check.log)
```
mpirun -np 2 test-env/bin/python -m pytest tests --only-mpi
```

**Comment by prs513rosewood** [comment]
Great ! Thanks for creating an AUR package, glad to see people use this code.
